name: eurec4a_intake

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0  # required to analyze which files are modified in this branch
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies (pip)
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Test with pytest
      run: |
        pip install pytest pytest-xdist sh
        # the intake-xarray puts it's source in src/ because we're installing
        # from github directly, but we don't want to run its tests
        python -m pytest --ignore=src/ -m modified_on_branch -n 20
