name: Validate JSON

on: push

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Validate JSON
        uses: walbo/validate-json@v1.1.0
        with:
          files: .zenodo.json
          schema: https://zenodo.org/schemas/deposits/records/legacyrecord.json
          fail-on-missing-schema: true
          strict: true
